npmRegistryServer: https://registry.npmjs.org
npmScopes:
  allergan-data-labs:
    npmRegistryServer: https://npm.pkg.github.com/
    npmAuthToken: ${GITHUB_PACKAGES_TOKEN}
  adl:
    npmRegistryServer: https://registry.npmjs.org/
    npmAuthToken: ${NPM_TOKEN}
    npmAlwaysAuth: true
